spring:
  application:
    name: Restaurant
  datasource:
    url: jdbc:postgresql://localhost:5432/Restaurant
    username: waiter
    password: secure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081